server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      database: ${db.database:blueboz}
      username: ${db.username:blueboz}
      password: ${db.password:chenchen}
      host: ${db.host:121.37.202.206}
      port: ${db.port:27017}
      authentication-database: ${db.authdb:admin}
  resources:
    static-locations:  file://${staticLoc:/Volumes/Mac/Code/Others/osgiProj/robotComSysServer/upload10/}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
file-service:
  profile: ${staticLoc:/Volumes/Mac/Code/Others/osgiProj/robotComSysServer/upload/}
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){red} %clr(${LOG_LEVEL_PATTERN:%5p}){yellow} %clr(${PID:- }){green} %clr([%15.15t]){cyan} %clr(%L){blue} %clr(%-25logger{24}:){magenta} %clr(%m%n){faint}"
  level:
    root: ${loglevel:info}

