server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      database: blueboz
      username: blueboz
      password: chenchen
      host: 127.0.0.1
      port: 27017
file-service:
  profile: /Volumes/Mac/Code/Others/osgiProj/robotComSysServer/upload